// NIFTY pattern library — verbatim mock data, retained until /api/nifty/patterns
// covers every entry. Typed against PublicPattern from the public API surface.

import type { PublicPattern } from '@/lib/api/nifty';

export const patterns: PublicPattern[] = [

  // ─── CONFIRMED ────────────────────────────────────────────────────────

  {
    id: 'P14-A1',
    name: 'Peak-Score Ceiling State',
    tier: 'CONFIRMED',
    category: 'Peak/Trough',
    instances: 7,
    rule: 'When Net score reaches ≥+10, or Net = +9 as the 120-day high, the score has reached a fundamental ceiling. The ceiling is a state, not a point. Score peaks lead price peaks by 8-15 sessions in 6 of 7 confirmed instances. The ceiling state remains active until Net decays below the qualifying threshold.',
    example_dates: ['2023-12-14', '2024-09-27', '2025-05-02', '2025-06-27', '2025-10-23', '2026-02-06', '2026-04-21'],
    description: 'The most operationally important pattern in the system. When fundamentals have reached their ceiling, price is statistically likely to follow within 2-3 weeks. The pattern does not predict the magnitude of the subsequent decline — it identifies the zone where NIFTY price risk is highest. Decay velocity (from the Velocity sub-tool) modulates urgency: fast decay is more dangerous than slow decay.',
    drives_subtool: 'Peak Ceiling',
    status: 'Drives peak-score ceiling sub-tool. Live in scoring.',
    relevance_triggers: ['band:Strong Bullish', 'peak_score_active', 'velocity:decay'],
  },

  {
    id: 'P15-2',
    name: 'V-Bottom Discriminator',
    tier: 'CONFIRMED',
    category: 'Recovery',
    instances: 5,
    rule: 'At the moment of a technical V-bottom trough, Ind 9 raw composite classifies the structural validity: ≤ 0 = REAL (USD regime broken, recovery will sustain); +1 to +4 = AMBIGUOUS (recovery needs External flip to confirm); ≥ +5 = COUNTER-TREND (USD regime intact, bounce will fail).',
    example_dates: ['2024-04-04', '2024-12-14', '2025-09-12', '2026-04-07', '2026-04-02'],
    description: 'Answers the single most important question at a technical V-bottom: is this real or a trap? A V-bottom forming with USD regime still intact (Ind 9 raw ≥ +5) is the market attempting to recover against the macro — it fails. Real V-bottoms require USD already in retreat. The AMBIGUOUS zone (+1 to +4) is the honest gray area where the tool suspends judgment.',
    drives_subtool: 'V-Bottom',
    status: 'Drives V-Bottom discriminator sub-tool. Live in scoring.',
    relevance_triggers: ['band:Bearish', 'band:Strong Bearish', 'composition_flag:active'],
  },

  {
    id: 'P12-1',
    name: 'Fade-Into-Top',
    tier: 'CONFIRMED',
    category: 'Peak/Trough',
    instances: 5,
    rule: 'When Net score is in Strong Bullish band but decaying (velocity ≤ −0.15/day for ≥ 3 sessions), the score is fading into the top. Price may still be rising — this is the divergence moment. Score degrading ≥3 points over 10+ sessions while price remains near the high is a sell-into-strength signal.',
    example_dates: ['2024-10-15', '2025-03-08', '2025-07-11', '2026-01-30', '2026-04-27'],
    description: 'The operational implementation of peak ceiling awareness. Fade-into-top distinguishes between a fresh Strong Bullish (load exposure) and an expiring Strong Bullish (trim exposure). The key is the combination: band still Strong Bullish, but velocity negative and sustained. This combination has preceded 5 confirmed price tops. Used in conjunction with P14-A1.',
    drives_subtool: 'Peak Ceiling',
    status: 'In scoring. Contextual confirmation of P14-A1.',
    relevance_triggers: ['band:Strong Bullish', 'peak_score_active', 'velocity:decay'],
  },

  {
    id: 'P9-4',
    name: 'CONFLICT Regime — External Dominance',
    tier: 'CONFIRMED',
    category: 'Composite',
    instances: 4,
    rule: 'When External composite ≤ −3 while Domestic composite ≥ +3, a CONFLICT flag fires. Net score understates the bearish regime: External is the trade-relevant signal, Domestic provides a structural floor. Historical resolution: External eventually drags Net down to match its own reading within 4-6 sessions.',
    example_dates: ['2024-08-05', '2025-01-14', '2026-03-05', '2026-03-25'],
    description: 'The CONFLICT regime is when the tool is most likely to mislead if read at face value. A Net of +1 with Domestic +4, External −4 is not a Bearish state — it is an External-dominant bear state with a domestic structural floor. The floor matters for NIFTY recovery timing (domestic won\'t crash), but the external signal matters for near-term price direction.',
    status: 'Drives CONFLICT flag on Pulse. Live in scoring.',
    relevance_triggers: ['conflict_flag:active', 'external:negative_deep'],
  },

  {
    id: 'P15-7',
    name: 'Ind 4 GDP Saturation',
    tier: 'CONFIRMED',
    category: 'Structural',
    instances: 3,
    rule: 'When India GDP growth sustains ≥7.0% for 3+ consecutive quarters, the indicator saturates at maximum positive contribution. At saturation, GDP no longer drives score improvement — the marginal unit of additional macro improvement must come from external or CPI sources. Saturation phases typically last 2-4 quarters before mean reversion begins.',
    example_dates: ['2024-09-30', '2025-06-30', '2025-10-23'],
    description: 'India GDP above 7% is exceptional by global standards — but the scoring system has already priced it in at +1. Additional acceleration above 7% adds no further score uplift. Recognizing saturation matters because it resets expectations: even if GDP stays strong, Net cannot improve from this source.',
    status: 'In scoring. Structural awareness note.',
    relevance_triggers: ['indicator:Ind4:saturated'],
  },

  {
    id: 'P15-9',
    name: 'CPI Trajectory Rule — Disinflation Premium',
    tier: 'CONFIRMED',
    category: 'Composite',
    instances: 6,
    rule: 'When India CPI is falling ≥20 bps vs 3-month trailing average AND the level is within the 4-6% comfort zone, the trajectory component fires an additional +1. This is the disinflation premium — the market rewards not just where CPI is, but the direction it is moving. Trajectory reversals (CPI starts rising) immediately remove the premium.',
    example_dates: ['2024-10-14', '2025-01-13', '2025-04-14', '2025-07-14', '2025-10-14', '2026-04-12'],
    description: 'The trajectory component of Ind 3 is the most frequently volatile component in the domestic composite. It fires when CPI is clearly in the right zone AND moving in the right direction. The premium has fired 6 times in recent history, always coinciding with positive Domestic composite readings. Its removal (CPI stops falling or reverses) is a leading indicator of Domestic score decay.',
    status: 'In scoring. Trajectory component of Ind 3.',
    relevance_triggers: ['indicator:Ind3:trajectory_active'],
  },

  {
    id: 'P7-1',
    name: 'RBI Easing Cycle Unlock',
    tier: 'CONFIRMED',
    category: 'Structural',
    instances: 3,
    rule: 'When RBI cuts rates for the first time after a sustained hold period (≥12 months), Ind 7 score upgrades from 0 to +1, adding a structural +1 to Domestic composite. The upgrade is durable — it persists through the full easing cycle. Historical easing cycles have added 2-4 sessions of lagged momentum to NIFTY price after the score upgrade.',
    example_dates: ['2020-03-27', '2023-02-08', '2026-04-09'],
    description: 'The RBI cut unlock is one of the cleanest Domestic score upgrades in the system — it is definitively triggered, explicitly scored, and historically associated with positive price lag effects. The Apr 9, 2026 cut represents the third observed instance. The upgrade matters because it expands Domestic ceiling capacity: a +7 Domestic that was thought to be maxed out suddenly becomes possible.',
    status: 'In scoring. Structural upgrade event.',
    relevance_triggers: ['indicator:Ind7:rate_cut'],
  },

  // ─── OBSERVED ─────────────────────────────────────────────────────────

  {
    id: 'P22-5',
    name: 'Domestic Floor During Bear Phase',
    tier: 'OBSERVED',
    category: 'Bear Regime',
    instances: 3,
    rule: 'In bear phases (External ≤ −3), Domestic composite sustains at ≥+3 in 3 of 3 observed instances — even when price is falling sharply. The domestic floor prevents Net from entering deeply negative territory. The floor level matters: Domestic +5 or +6 means recovery requires only External to flip; Domestic +3 means recovery needs both composites to improve.',
    example_dates: ['2026-02-27', '2026-03-05', '2026-03-25'],
    description: 'India\'s structural growth story provides a macro floor that limits the depth of bearish readings. Even during Phase 22 (Iran War shock), Domestic never turned deeply negative. This is operationally useful: bear phases with high domestic floors recover faster. The observation drives conviction in recovery trades earlier than pure technicals would allow.',
    status: 'Cross-validation in progress. Will confirm at 5 instances.',
    relevance_triggers: ['domestic:floor_holding', 'external:negative'],
  },

  {
    id: 'P15-8',
    name: 'Ind 9 Full-Cycle Swing',
    tier: 'OBSERVED',
    category: 'Composite',
    instances: 2,
    rule: 'When Ind 9 raw composite swings ≥10 points peak-to-trough (or trough-to-peak) within a single phase, it signals a USD regime change — not just a correction. These full-cycle swings (e.g., +9 to −6 across Phase 22 to Phase 23) historically coincide with major directional changes in NIFTY. The swing must cross the 0-line to qualify.',
    example_dates: ['2025-07-11', '2026-04-10'],
    description: 'USD regime changes are the highest-impact external events for NIFTY macro scoring. A swing from strong-USD to weak-USD territory (crossing 0) adds multiple points to External composite rapidly. The challenge is identifying the swing in real-time — the pattern is most visible in retrospect. Early detection (when raw crosses +5 and is falling) is the current operational approximation.',
    drives_subtool: 'Composition',
    status: 'Drives composition flag activation logic.',
    relevance_triggers: ['ind9_raw:large_swing'],
  },

  {
    id: 'P22-3',
    name: 'Ind 9 Near-Threshold Ambiguity',
    tier: 'OBSERVED',
    category: 'Composite',
    instances: 2,
    rule: 'When Ind 9 raw sits in the +1 to +4 range, the score is AMBIGUOUS — not strongly USD-weak or USD-strong. In bear phases, this zone corresponds to the V-Bottom AMBIGUOUS verdict. In bull phases, it corresponds to External composite compression (Ind 9 contributing 0 instead of +1 or +2). Ambiguity reduces External ceiling capacity.',
    example_dates: ['2026-04-02', '2026-04-07'],
    description: 'The ambiguity zone is not a neutral state — it is an unresolved state. The tool explicitly acknowledges when it cannot classify the USD regime. This intellectual honesty prevents false confidence: in the ambiguous zone, the V-Bottom discriminator suspends judgment, and the composition flag is inactive. Watching for resolution (raw breaking below 0 or above +4) is the correct next step.',
    drives_subtool: 'V-Bottom',
    status: 'Drives AMBIGUOUS verdict in V-Bottom discriminator.',
    relevance_triggers: ['ind9_raw:near_threshold'],
  },

  {
    id: 'P19B-2',
    name: 'External Turning Point — Velocity Confirmation',
    tier: 'OBSERVED',
    category: 'Recovery',
    instances: 2,
    rule: 'When External composite begins recovering from ≤ −3, the first session where Velocity reading upgrades from Warning/Alert tier to Slow Repair or better confirms the turning point. Without velocity confirmation, early External recovery readings are noise. With confirmation (+Vel ≥ +0.30/day), the turning point is structurally real.',
    example_dates: ['2025-09-19', '2026-04-10'],
    description: 'External turning points have proven difficult to identify at the time — they often look like brief bounces before resuming the downtrend. The Velocity sub-tool provides the confirmation mechanism: sustained positive velocity across 2-3 sessions means the recovery is directional. This pattern drives the operational rule: do not call External recovered until velocity confirms.',
    drives_subtool: 'Velocity',
    status: 'Drives velocity confirmation logic for External recovery.',
    relevance_triggers: ['external:turning', 'velocity:high'],
  },

  {
    id: 'P23-1',
    name: 'Ceiling Recovery Velocity',
    tier: 'OBSERVED',
    category: 'Recovery',
    instances: 2,
    rule: 'When Net score recovers from a confirmed V-bottom (REAL verdict) at velocity ≥ +0.75/day sustained over 3+ sessions, the recovery is a ceiling recovery — the highest possible velocity tier. Ceiling recovery velocities have historically been followed by the strongest bull phases in the dataset. The Apr 10, 2026 print (+0.75/day, 3 sessions) is the latest confirmed instance.',
    example_dates: ['2025-09-26', '2026-04-10'],
    description: 'V-bottom recoveries come in different speeds. A ceiling recovery velocity means the market is re-pricing fundamentals very rapidly — unusual and historically bullish. The two observed instances both followed real V-bottoms (Ind 9 raw ≤ 0 at the trough) and both were followed by Strong Bullish band entries within 8 sessions.',
    drives_subtool: 'Velocity',
    status: 'Velocity sub-tool historical annotation.',
    relevance_triggers: ['velocity:ceiling_recovery'],
  },

  {
    id: 'P18-1',
    name: 'Post-V-Bottom Band Walk',
    tier: 'OBSERVED',
    category: 'Recovery',
    instances: 3,
    rule: 'Following a confirmed REAL V-bottom (Ind 9 raw ≤ 0), Net score walks through bands sequentially: Bearish → Bullish → Strong Bullish over 3-5 scoring sessions. Each band is held for 1-3 sessions before the next upgrade. Skipping a band (Bearish directly to Strong Bullish) has not been observed.',
    example_dates: ['2024-04-10', '2025-09-22', '2026-04-10'],
    description: 'The band walk is the macro recovery signature. It reflects the gradual normalization of External indicators as USD weakens and risk appetite returns. The predictable sequence is operationally useful: after V-bottom, the user can set price targets corresponding to each band upgrade milestone. The walk duration (sessions per band) varies by recovery velocity.',
    status: 'Structural recovery template.',
    relevance_triggers: ['band:Bullish', 'band:Neutral', 'phase:post_v_bottom'],
  },

  {
    id: 'P12-2',
    name: 'Clean Bullish State',
    tier: 'OBSERVED',
    category: 'Composite',
    instances: 3,
    rule: 'When all six Domestic indicators and at least four External indicators are positive, and no sub-tool flags are active, this is a Clean Bullish State. Clean states are characterized by low conflict, positive velocity, and the highest historical forward returns in the dataset. Clean states are rare — they typically last 2-5 scoring sessions before a flag or indicator flip disrupts them.',
    example_dates: ['2025-06-13', '2025-10-09', '2026-04-21'],
    description: 'The cleanest possible macro setup. Every domestic indicator firing, External broadly positive, no alerts. This is the state where NIFTY historically produces the highest-quality trending moves. The challenge is that clean states are by definition late in the cycle — they occur near peaks. Using them as loading opportunities requires caution.',
    status: 'Structural quality classification.',
    relevance_triggers: ['band:Bullish', 'band:Strong Bullish', 'clean_bullish:active'],
  },

  {
    id: 'P15-11',
    name: 'Bear Regime Floor Pattern',
    tier: 'OBSERVED',
    category: 'Bear Regime',
    instances: 2,
    rule: 'In confirmed BEAR_DEEP regime (bucket classification), when Net score reaches −2 to −3 AND Domestic composite holds ≥ +2, the bear floor is forming. The floor has held in both observed instances — Net has not breached −4 with Domestic above 0. This provides the structural minimum for bear severity assessments.',
    example_dates: ['2026-03-05', '2024-08-05'],
    description: 'Bear regime floors are one of the few structural limits in the scoring system. When Domestic fundamentals remain intact (GDP, PMIs, CPI), the systemic floor prevents catastrophic Net readings. This creates an asymmetry: bear phases with strong Domestic fundamentals have defined floors; bear phases with Domestic deterioration (India CPI spike, GDP shock) would have no such floor.',
    status: 'Bear regime structural analysis.',
    relevance_triggers: ['bucket:BEAR_DEEP', 'band:Bearish', 'band:Strong Bearish'],
  },

  {
    id: 'P22-1',
    name: 'External Leads Net Down at Top',
    tier: 'OBSERVED',
    category: 'Peak/Trough',
    instances: 2,
    rule: 'External composite begins decaying 1-2 scoring sessions before Net peaks. When External drops while Domestic holds, Net appears stable — but External is the leading indicator. Confirmation: External −1 or more while Net is still ≥+9 (i.e., Domestic carrying the Net). This configuration preceded both observed Net peaks.',
    example_dates: ['2026-01-30', '2025-07-25'],
    description: 'The tell before the top. External indicators (USD, VIX, crude, INR) respond faster to global regime changes than Domestic (CPI, PMI, GDP, GST are monthly cadence). When External starts dropping while Domestic holds, Net looks stable — but the decay has begun. P22-1 is the early warning system for P14-A1 (Peak Ceiling) and P12-1 (Fade-into-Top).',
    drives_subtool: 'Peak Ceiling',
    status: 'Early warning for peak ceiling. Contextual.',
    relevance_triggers: ['band:Bullish', 'band:Strong Bullish', 'external:decaying'],
  },

  {
    id: 'P21-C',
    name: 'Section 9F Composite Texture — Always Read Both',
    tier: 'OBSERVED',
    category: 'Operational',
    instances: 12,
    rule: 'Always read Domestic and External composites separately. Net alone hides the regime. A Net of +4 with Domestic +6, External −2 is structurally different from Net +4 with Domestic +2, External +2 — the first has a structural floor (recovery likely), the second has fragility (could go either way). This operational rule applies to every scorecard without exception.',
    example_dates: ['2026-04-27', '2026-03-05', '2025-10-23', '2025-06-27', '2025-01-14'],
    description: 'The foundational operational rule of the scoring system. Net is a summary; Section 9F is the regime. This pattern is ALWAYS relevant because the Domestic/External split is always informative. Never make a NIFTY macro judgment from Net alone — the split changes everything about the read.',
    status: 'Operational foundation. Always relevant.',
    relevance_triggers: ['always_relevant'],
  },

  {
    id: 'P19A-1',
    name: 'Caution Band — False Ceiling',
    tier: 'OBSERVED',
    category: 'Peak/Trough',
    instances: 2,
    rule: 'When score sits in Caution band (Net = 3) for 2+ consecutive sessions without sub-tool flags active, this is a false ceiling — not a real top. The score is in transition, not at a macro peak. Both observed instances resolved upward (score entered Neutral or higher within 3 sessions). Caution band without peak ceiling flag = neutral-to-bullish transition, not a top.',
    example_dates: ['2025-07-11', '2024-07-19'],
    description: 'Caution band readings are often misread as bearish signals. They are transition states. Without sub-tool confirmation (peak ceiling, conflict flag), a Caution reading simply means Net is in a neutral zone between Bearish and Neutral — not structurally weak, not strong. The false ceiling pattern reminds users not to overweight the Caution label.',
    status: 'Transition state clarification.',
    relevance_triggers: ['band:Caution'],
  },

  // ─── HYPOTHESIS ───────────────────────────────────────────────────────

  {
    id: 'P14-5',
    name: 'Ind 12 First Positive — INR Regime Shift',
    tier: 'HYPOTHESIS',
    category: 'Composite',
    instances: 1,
    rule: 'When Ind 12 (INR/USD) turns positive for the first time after 3+ sessions at 0 or negative, it may signal an INR regime shift — USD weakness becoming structural. The single observed instance (Apr 14, 2026: INR ₹83.0 after being pressured at ₹84-85 range) preceded a 2-session External composite upgrade.',
    example_dates: ['2026-04-14'],
    description: 'Single-instance hypothesis. INR is a composite reflection of USD regime, India current account, and global risk appetite. When INR strengthens from a structurally weak position, it simultaneously removes a negative External score and adds a positive one — a 2-point External swing from a single indicator. If this pattern holds (INR regime flip = sustainable +2 to External), it would be among the most operationally useful early signals.',
    status: 'Awaiting second instance for cross-validation.',
    relevance_triggers: ['indicator:Ind12:first_positive'],
  },

  {
    id: 'P18-6',
    name: 'Composition Flag — DEMAND_DESTRUCTION Equity Signal',
    tier: 'HYPOTHESIS',
    category: 'Structural',
    instances: 1,
    rule: 'When composition flag fires DEMAND_DESTRUCTION (GL_neg ≥ 6, I_neg = 0), USD weakness is growth/labor driven — not inflation driven. Hypothesis: this composition produces more sustained NIFTY equity tailwinds than INFLATION_LED weakness, because demand destruction in the US improves India\'s relative growth premium without raising India\'s import costs.',
    example_dates: ['2025-06-27'],
    description: 'The composition flag\'s potential predictive value for equity direction. If the mechanism holds, DEMAND_DESTRUCTION USD weakness is better for NIFTY than INFLATION_LED weakness (which still raises commodity costs). Only one instance with sufficient data quality to test — the Jun 27, 2025 Phase 19A peak. Awaiting Phase 23 resolution to cross-validate.',
    drives_subtool: 'Composition',
    status: 'Research hypothesis. Awaiting second instance.',
    relevance_triggers: ['composition_flag:active'],
  },

  {
    id: 'P22-4',
    name: 'Flat Velocity in Bear — Compression Before Break',
    tier: 'HYPOTHESIS',
    category: 'Bear Regime',
    instances: 1,
    rule: 'When Net score velocity flattens (→ Flat tier, −0.10 to +0.10/day) for 3+ sessions while band remains Bearish or Strong Bearish, the compression may precede a directional break. Hypothesis: flat velocity in bear regimes is not equilibrium — it is compression before either further deterioration or recovery.',
    example_dates: ['2026-03-15'],
    description: 'Single instance observed in Phase 22. Velocity went flat at Net −1 for 3 sessions before the Mar 25 deterioration to −3. Hypothesis: flat velocity in bear regimes is not rest — the underlying forces (USD, crude, FII flows) are still moving, and the flat reading reflects offsetting indicators canceling each other. When one side gives, the velocity breaks hard.',
    drives_subtool: 'Velocity',
    status: 'Hypothesis. Requires 2+ instances.',
    relevance_triggers: ['bucket:BEAR_DEEP', 'band:Bearish', 'velocity:flat'],
  },

  {
    id: 'P22-2',
    name: 'CONFLICT + India VIX Spike — False Net Read',
    tier: 'HYPOTHESIS',
    category: 'Bear Regime',
    instances: 1,
    rule: 'When CONFLICT flag is active AND India VIX is above 25, Net score may dramatically understate bearish severity. The single observed instance (Mar 5, 2026: Net −3, VIX 34, CONFLICT active) showed price falling 12% while Net appeared bounded at −3. Hypothesis: VIX above 25 during CONFLICT amplifies External regime signal beyond what Net captures.',
    example_dates: ['2026-03-05'],
    description: 'The combination of CONFLICT regime and extreme fear (VIX > 25) may create a reading environment where Net score is structurally misleading. The scorecard shows −3; the actual macro regime may be worse. This hypothesis is driven by the extreme disconnect between Mar 5 price action (−12%) and the seemingly moderate Net reading. Under investigation.',
    status: 'Hypothesis. Single instance, high-impact scenario.',
    relevance_triggers: ['conflict_flag:active', 'volatility:high'],
  },
];
